name: test
on:
    push:
    pull_request:
jobs:
    lint:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-node@v4
              with:
                  version: latest
            - name: Install modules
              run: npm install
            - name: Run ESLint
              run: npm run lint
    format:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-node@v4
              with:
                  version: latest
            - name: Install modules
              run: npm install
            - name: Run Prettier
              run: npm run format
    compile:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-node@v4
              with:
                  version: latest
            - name: Install modules
              run: npm install
            - name: Run tsc
              run: tsc --noEmit
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-node@v4
              with:
                  version: latest
            - name: Install modules
              run: npm install
            - name: Run build
              run: npm run newbuild
